### ISSUE TITLE
Mob Hunt Quest with rewards won't complete

### ISSUE THREAD

**Issue by Dream-Master** [Funwayguy/BetterQuesting#33] opened 2016-05-17 19:55 UTC
Every time when I try to complete a Mob Hunt Quest it not give me the reward after I kill 5 Pigs for an example.
If I kill the sixth pig the reward bottom can be pushed. Same with auto claim  you got the item one Kill later. The same is with Sheep's I tested it. For me it looks like the final Kill updates the Quest and complete it but without give me the reward.

Using:

Minecraft 1.7.10 Forge 1614
BetterQuesting-1.0.92
StandardExpansion-1.0.68
Questbook 1.1.0
RFExpansion-1.0.7
Theme 1.0.0

**Comment by Funwayguy** [comment] 2016-05-18 01:07
Found the cause of this. Turns out it happens with meeting tasks too. I'll be pushing an update to fix this pretty soon.

EDIT: Fix posted. Closing issue

**Closed as completed** 2016-05-18 03:51 UTC
Labels: bug
