### ISSUE TITLE
Zoom-to-fit ignores the open Quest Lines pane.

### ISSUE THREAD

**Issue by Slyklaw** [Funwayguy/BetterQuesting#692] opened 2020-01-31 04:42 UTC
Open the Quest Lines pane, then click zoom-to-fit.

![2020-01-31_11 39 58](https://user-images.githubusercontent.com/44900062/73513017-791ef100-441e-11ea-9dae-8eb762fe395b.png)

It would be nice if the zoom allowed one to see all the quests when the Quest Lines pane is open.

**Comment by Funwayguy** [comment] 2020-01-31 05:24
I'll consider it. I dont really see this as a necessary change. It's easy enough to just zoom or close the pane.

**Comment by mellamokb** [comment] 2020-02-01 19:18
Second this.  I noticed when DDSS upgraded, suddenly the Quest Pane didn't stay locked open.  Often I'm hunting down a specific relevant quest and it's annoying as hell to click twice every time you want to review a quest line.  So I was positively elated to discover the new lock icon, only to discover the same issue as OP.  Just my additional vote to adopt this.  Thanks!!

**Comment by Spongman** [comment] 2020-03-01 20:54
yeah, this is pretty annoying. you can't scroll the contents of the pane out from under the pane either, because it's not taking the  smaller size of the visible window into account. this is definitely a regression from the previous UI.

this is scrolled all the way to the right:

![image](https://user-images.githubusercontent.com/1088194/75633738-74d02a00-5bbc-11ea-9140-a1aec5eaa056.png)

it's impossible to see the quests underneath without messing about repeatedly opening/closing the qust line panel, or zooming in & out all the time. it's just a whole bunch extra work just to see something that shouldn't be hidden in the first place. what's worse is that it doesn't remember the scroll/pan settings of each quest line page, so you have to do this EVERY TIME you switch between lines.

i'm sorry, but you just killed this modpack for me. i'm going to have to go find one that uses the FTB quest mod instead...

**Comment by Funwayguy** [comment] 2020-03-01 22:22
This was fixed weeks ago... 
If something as simple as an overlap is enough to make you quit playing a modpack then by all means go play another. I'm sure there's someone that caters to your excessively high standards.

**Closed as completed** 2020-03-01 22:28 UTC

**Comment by Spongman** [comment] 2020-03-02 01:33
no need to take it personally, it's just a bug report.

actually. i found a mod that converts BQ quests to FTB, so i'm using that now, thanks.

**Comment by Funwayguy** [comment] 2020-03-02 03:36
There is a major difference between constructive criticism and generally just commenting to complain further without offering any solutions.

Slyklaw stated a simple concern and offered a solution.

mellanmokb further elaborated on how this affects their gameplay and voted on the aforementioned solution.

Not only did you misinterpret the original request which was just to have zoom-to-fit be aware of the tray, you went off stating other semi-unrelated issues that somehow "killed" the pack in exaggeration. You also didn't check if there were updates to solve your issue before impulsively jumping into this issue thread.

I will happily work with people who are willing to contribute to improving BQ in a constructive manner but this is not how to do so.

**Comment by Spongman** [comment] 2020-03-02 04:26
i guess you didn't understand the points i was trying to make, then. sorry about that.
