### ISSUE TITLE
[1.7.10] Broke Inventory Crafting

### ISSUE THREAD

**Issue by brunoxkk0** [Funwayguy/BetterQuesting#605] opened 2019-05-29 17:50 UTC
After i have updated the Better Questing for 3.0.297 version, any player of my server who's try use then is disconnect with internal error.
If i are on creative inventory, and try to clean my inventory holding shift is disconnected too.

it's thrown this error on console
`[13:13:04] [Server thread/WARN]: Failed to handle packet for /<IP:PORT>
java.lang.ClassCastException: bq_standard.handlers.PlayerContainerListener cannot be cast to net.minecraft.entity.player.EntityPlayerMP
	at net.minecraft.inventory.ContainerPlayer.func_75130_a(ContainerPlayer.java:105) ~[aap.class:?]
	at net.minecraft.inventory.InventoryCrafting.func_70299_a(InventoryCrafting.java:153) ~[aae.class:?]
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77) ~[aay.class:?]
	at net.minecraft.inventory.Container.func_75144_a(Container.java:418) ~[zs.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2075) ~[nh.class:?]
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32) ~[ix.class:?]
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10) ~[ix.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]`

BetterQuesting-3.0.297.jar
StandardExpansion-3.0.155.jar

**Comment by Funwayguy** [comment] 2019-05-31 01:59
What version of Forge are you using? I can't recreate this in 1558 and that error points to something that doesn't exist at least in that version.

**Comment by brunoxkk0** [comment] 2019-05-31 02:54
I'm using forge 1614, and the server is running Thermos 58.

**Comment by juanmuscaria** [comment] 2019-06-01 23:34
This problem is caused by a thermos patch [here](https://github.com/CyberdyneCC/Thermos/blob/master/patches/net/minecraft/inventory/ContainerPlayer.java.patch#L58)
I've created a core mod to fix this problem  [here](https://github.com/juanmuscaria/Gambiarra-BetterQuesting)
Sorry, my English is not very good.

**Comment by Funwayguy** [comment] 2019-06-02 02:27
In that case I can close this issue seeing as this stems from Thermos making unchecked casting (which judging by the comment in code was known unsafe). I won't be rolling BQ's implementation back to 'fix' this either.

**Closed as completed** 2019-06-02 02:27 UTC
