### ISSUE TITLE
[1.12.2] Crash rendering screen

### ISSUE THREAD

**Issue by MasterEnderman** [Funwayguy/BetterQuesting#361] opened 2018-04-19 23:59 UTC
Crash Report: https://pastebin.com/8T02D6RF
Forge: 14.23.3.2668
BetterQuesting: 3.5.251

**Comment by Funwayguy** [comment] 2018-04-20 00:05
I was somewhat expecting this to happen when I wrote [the changelog](https://minecraft.curseforge.com/projects/better-questing/files/2553231) however this is probably a little worse than I was intending and occurs within new code so I guess in this case I _will_ have to look into the cause.

**Comment by Funwayguy** [comment] 2018-04-20 01:19
Found and fixed. Screwed up an edge case on empty carriage returns in mutli-line text editors. Will post the build up later today.

**Comment by MasterEnderman** [comment] 2018-04-23 17:35
The crash is fixed but every time i open a quest the description is missing, but the console is spamed with
```
[main/ERROR] [betterquesting]: LINE COUNT MISSMATCH (2 != 1) ON TEXT: 
```

**Comment by Funwayguy** [comment] 2018-04-23 23:20
FFFFFFFFFudge. How is that still happening?

Can you post the `.json` file so I can test it in my development environment.

**Comment by MasterEnderman** [comment] 2018-04-26 11:19
i fixed it by copying the text out of the ingame gui in an editor and putting it back in.

**Comment by Funwayguy** [comment] 2018-04-26 11:26
I would have preferred to be able to recreate it myself so I could fix it in case it happened again for other people. I'll close this issue for now seeing as the original issue is fixed.

**Closed as completed by Funwayguy** 2018-04-26 11:26 UTC
