### ISSUE TITLE
[1.10.2]Cannot leave questing party (SPONGE SERVER)

### ISSUE THREAD

**Issue by Column01** [Funwayguy/BetterQuesting#214] opened 2017-07-07 03:07 UTC
As the title says, I cannot leave my questing party on one of my Network's servers. I click the button and nothing happens. We are running sponge on the server, and I have not tested in a normal forge server. Please let me know if anyone else is having this issue. Thanks!
-Colin
BETTER QUESTING VERSION: 2.3.234
MOD LIST: https://pastebin.com/r6cbjZtm 
SCREENSHOTS:
http://i.imgur.com/NlCnqsA.png

**Comment by Jaskirat-Boparai** [comment] 2018-07-07 14:09
This is also an issue with our FTB: Continuum Server. A player is trying to leave their questing party but cannot, clicking the leave button has no effect. Furthermore, the party leader is not available to kick the person out of the party, meaning the player is stuck in this party, with administration not being able to assist as, according to your wiki: "server operators do not have the ability to tamper with questing parties."

BQ version: 3.5.259
Sponge version: spongeforge-1.12.2-2705-7.1.0-BETA-3265.jar

Perhaps adding the ability for server operators to force kick a player from the questing party they are in can be done, if the actual issue cannot be solved? This seems like a convenient feature for operators to have anywho.

Thank you ^_^

**Comment by Funwayguy** [comment] 2018-07-07 14:17
Actually the documentation is somewhat outdated. In newer versions OPs can invite themselves to parties with full owership level privileges.

Regardless, the issue here is that I don't do support for sponge. If you can recreate it on a standard forge server I can consider looking into it more next update.

If you absolutely must force modify parties you can do so from the file in the world folder while the server is down.

**Comment by 0xpr03** [comment] 2018-08-09 20:25
Same problem here, can't leave party, FTB Continuum 1.4.1
No sponge.
Edit: I was able to leave the party when OPing the User.

**Comment by Funwayguy** [comment] 2018-08-10 04:40
What version of BQ is Continuum using?

**Comment by 0xpr03** [comment] 2018-08-13 22:03
Better Questing 3.5.262
which runs on mc 1.12.2
forge 14.23.4.2730
Edit: I wasn't the creator of the party I wanted to leave.

**Comment by Funwayguy** [comment] 2018-08-19 09:32
Finally found and fix it for next release. Turns out it was a `==` check not being a `.equals()` when processing the kick/leave requests (easy to assume the checks were the same and worked as intended). Never actually encountered this issue in testing before because I always had commands enabled which implied OP status over the party actions.

**Comment by 0xpr03** [comment] 2018-08-19 09:39
Thanks, though I won't be able to test it.
(It'll take until that lands in a modpack & you basically don't upgrade modpack servers if you can..)

**Comment by Funwayguy** [comment] 2018-08-20 03:41
Fix included in build 263. Closing issue.

**Closed as completed by Funwayguy** 2018-08-20 03:41 UTC

**Comment by Column01** [comment] 2019-01-07 18:10
Hey @Funwayguy,
Sorry to re-open this issue.
I have experienced this yet again in 1.12 with version 280.
I tested in singleplayer and it works, but you need to click out of the party tab on the questbook and back in for it to refresh which, if I remember correctly, was not the case in older versions. From what I can tell that might be the issue, its just not updating on the client fast enough so when it re-syncs to the client it doesn't actually remove them from the party. I have not tested on a normal forge server to confirm or not (Still sponge server).
