### ISSUE TITLE
Designer and Edit issues

### ISSUE THREAD

**Issue by ghost** [Funwayguy/BetterQuesting#559] opened 2019-03-04 01:08 UTC
When editing quests in the designer, you have to back out of it completely and go back in before you can edit a quest in it again (or interact with quests in any way). Quests edit fine outside of the designer.

Also, when changing font colors, the editor deletes the selected line, forcing you to type it all over again if you want a different color.

BQ: 3.5.292
BQSE: 3.4.152

while you're in there, could you make it default to selecting the cursor so that you can go straight into editing existing quests with one less click? ;)

**Comment by Funwayguy** [comment] 2019-03-04 02:51
Would prefer these issues were separated into their own threads so I can address them individually.

1) Duplicate of #558 which I'm already done fixing in dev

2) The buttons are just an "insert" for a formatting code so having text selected would replace it. I may add support for automatically adding codes at the start and end of the selected block but that's difficult given the Minecraft's implementation of formatting codes and how to revert to the previous combination.

3) It doesn't do that the first time the designer opens but returning from a previous edit should already have the last tool as the active one. I do need to fix the tab not reflecting that though.

**Comment by ghost** [comment] 2019-03-04 03:15
My apologies, I just ran into them at the same time. I'll keep this in mind for the future.

1-noted, my fault, should've used search. d'oh

2- fair enough. The main issue is when reformatting multiple lines, it will apply formatting to all lines thereafter up until it hits one with formatting, as when you start typing with default "white" no formatting is applied. It might be easier to set it so that applying formatting ignores any already typed text and only applies to what you're about to type.

3-could be related to 1. I seem to recall that it used to stay pressed, but I could be wrong.

**Comment by Funwayguy** [comment] 2019-03-04 03:47
The no-formatting part when switching colours is actually a vanilla thing. I don't understand why it's like that but changing colours erases any additional active formatting states such as bolding, underlines and italics (according to the wiki this is intended behaviour despite it seeming like more of a bug).

PS: Just uploaded build 293 which resolves issues (1) and (3)

**Closed as completed by Funwayguy** 2019-03-04 03:47 UTC
