### ISSUE TITLE
Other player can’t unlock quests in LAN multiplayer

### ISSUE THREAD

**Issue by Dimentive** [Funwayguy/BetterQuesting#562] opened 2019-03-06 16:28 UTC
I’m playing the [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) modpack (version 1.60, the latest version as of today) with Better Questing version 3.5.293 (latest version as of today) locally with a friend via LAN, and while I, the host of the LAN world, can unlock quests just fine, my friend can’t unlock any quests when he has the correct items. He could only complete the starter quests that don’t require any items to get the reward, but he can’t complete any other quests whatsoever.

[I posted this issue on the Enigmatica 2 GitHub repository](https://github.com/NillerMedDild/Enigmatica2/issues/373) and was told by @NillerMedDild that quests don’t work properly over LAN. I can try setting up a local server, but I’d rather not if it can be avoided, as I prefer playing over LAN due to the conveniency.

Is there something that I can do to fix this problem? If not, I would be more than happy if a fix for this bug could be incorporated into the Better Questing mod, as it’s hands down one of my favourite mods.

**Comment by Yakaita** [comment] 2019-03-08 01:27
I also play a modpack with LAN but the other guy can get the quests.
I'm not playing the Enigmatica 2 pack I'm playing my own pack A Collectors Paradise.
Maybe this is an issue related to Enigmatica 2 with some sort of mod conflict or something

**Comment by Funwayguy** [comment] 2019-03-08 01:49
One of the only cases where I believe a mod conflict would have potential side effects like this is if the broken tasks in question were crafting tasks and and another mod is poorly tampering with the crafting event hook without taking LAN play into account.

There's more than likely something much more subtle at play here. I've already located a few minor progression tracking issues with retrieval tasks but so far nothing substantially broken in crafting tasks besides some minor sync issues which a manual detect shouldn't be affected by.

**Comment by NielsPilgaard** [comment] 2019-03-08 05:08
Did the group detect logic change?

**Comment by Funwayguy** [comment] 2019-03-08 05:13
Yes and no. It's going to change in 294 because it's currently broken and behaving backwards in places (not really sure how it ever worked honestly). It might be contributing to some of the progression issues but I can't be sure if it's the root cause. I might just give you and @Dimentive an early test build with fixes for that and a few other minor things and see how that behaves.

**Comment by NielsPilgaard** [comment] 2019-03-08 05:29
Multiple people have told me that setting groupDetect to false makes quests completable, so it could definitely be the cause. I wouldn't mind doing some testing if I can make time for it today :)

**Comment by Funwayguy** [comment] 2019-03-08 05:35
Sounds about right from what I've seen in code. Group detect erasing partial progress and refusing additive party progression for whatever reason.

Currently just stumbled into recreating [this issue](https://github.com/Funwayguy/BetterQuesting/issues/561#issuecomment-470809065) while testing the group detect fix but I'll get you a new test build while I debug this new weirdness.

**Comment by Funwayguy** [comment] 2019-03-08 06:29
@NillerMedDild @Dimentive Can you test this early build for me and let me know how that goes for you and your friend? Should be fine to run it off the existing 3.5.293 base mod.

[StandardExpansion-3.4.153.jar.zip](https://github.com/Funwayguy/BetterQuesting/files/2944607/StandardExpansion-3.4.153.jar.zip)

**Comment by NielsPilgaard** [comment] 2019-03-08 07:05
On it :)

**Comment by NielsPilgaard** [comment] 2019-03-08 07:31
That build did not fix quest completion, not even with groupDetect set to false.

**Comment by NielsPilgaard** [comment] 2019-03-08 07:34
Some quests can be completed, but so far only 30%, and this is in single player.

**Comment by Funwayguy** [comment] 2019-03-08 07:43
_sigh_

I'm going to have to load up a copy of Enigmatica 2 and speed run it in creative to see first hand what exactly is breaking and why. My poor dev laptop is not going to like this...

**Comment by NielsPilgaard** [comment] 2019-03-08 08:11
The bug should also be present in the Light version, https://minecraft.curseforge.com/projects/enigmatica2light, if you update BQ, I think your dev laptop would like that a bit more :)

**Comment by Funwayguy** [comment] 2019-03-08 08:16
Yea loading that version now after the standard one ate through 14GB of RAM somehow. Minecraft really doesn't like running packs without the modified Java arguments it seems.

**Comment by NielsPilgaard** [comment] 2019-03-08 08:49
Well allocating 14GB without GC arguments usually doesn't work. 7GB should be perfect.

**Comment by Funwayguy** [comment] 2019-03-08 09:23
Oh wow I broke detection of... everything. Welp good thing that was just a test build. I'll go figure out what I missed inbetween fixing group detect.

EDIT: Found the error. My new math was dumber than the first.
I WRITE GUD CODE
_facedesks in embarrassment_

**Comment by Funwayguy** [comment] 2019-03-08 10:49
@NillerMedDild @Dimentive 

Let's try this again shall we.
[StandardExpansion-3.4.153.jar.zip](https://github.com/Funwayguy/BetterQuesting/files/2945456/StandardExpansion-3.4.153.jar.zip)

**Comment by NielsPilgaard** [comment] 2019-03-08 13:52
Woohoo! So far so good!

**Comment by NielsPilgaard** [comment] 2019-03-08 13:54
Auto detect worked with all quests I was unable to complete during previous tests, I'd call this a fix :D

**Comment by Dimentive** [comment] 2019-03-08 13:56
That’s awesome! Thank you so much, Funwayguy!

I’ve yet to test this myself, but once my game has loaded, I will test it with my friend and see if it works. If it worked for Niller, it’ll probably work for me, though.

**Comment by Funwayguy** [comment] 2019-03-08 13:58
That's great but I'll wait for @Dimentive and their friend to give it a test under LAN conditions to see if it has indeed fixed the original issue.

**Comment by Dimentive** [comment] 2019-03-08 14:49
My friend can unlock every quest he’s tried so far with the 3.4.153 build!

Thanks again, Funwayguy! I really appreciate the fix. ❤️ 👍

**Comment by Dimentive** [comment] 2019-03-08 19:40
My friend just tried to complete the “Barista Trainee” quest, which requires a Coffee Maker from Actually Additions and gives him 16 Coffee Beans, but it doesn’t work. This is the only quest that doesn’t work for him so far after we updated to the new build of Better Questing that you provided.

This is one of the quests he tried completing before we updated to the new build, and it’s still unobtainable for him. I’m not sure if this specific quest is broken and it’s a problem on [Enigmatica 2’s](https://minecraft.curseforge.com/projects/enigmatica2) side, or if it’s another bug in the mod. I, the host of the LAN world, don’t have a Coffee Maker myself yet, so I’m not sure if I’ll be able to complete the quest, but I haven’t _not_ been able to complete any quests so far, unlike my friend.

Oh, and I should mention that before we updated to the new Better Questing build, my friend completed the “Vanilla Meal” quest in the modpack, which is a quest that gives you several food items and makes you choose between four steak and 16 bread. In addition to that, he could complete quests that didn’t require any items but rather just the press of a button, but he couldn’t complete any of the other quests that he tried. Now, after updating to the new build, he can complete every quest he’s tried except for that Coffee Maker quest, and there might be more quests that he can’t obtain later on, but that I’m not sure of.

Nevertheless, we’re very glad that most of the quests work for him now.

**Comment by NielsPilgaard** [comment] 2019-03-08 20:04
The Barista Trainee quest does not have any known issues, but I can't rule out that it is an Enigmatica issue atm.

**Comment by Dimentive** [comment] 2019-03-08 22:34
Every other quest that he has tried has worked for him so far—just not the Barista Trainee quest. So I’m not sure.

His Coffee Machine has no liquids in it. Maybe the Coffee Machine required has some other NBT data and thus requires liquid to be in it? I don’t know; probably not.

**Comment by Dimentive** [comment] 2019-03-08 22:34
Every other quest that he has tried has worked for him so far—just not the Barista Trainee quest. So I’m not sure.

His Coffee Machine has no liquids in it. Maybe the Coffee Machine required has some other NBT data and thus requires liquid to be in it? I don’t know; probably not, as it probably would’ve been reported on the Enigmatica 2 GitHub repository by now.

**Comment by Funwayguy** [comment] 2019-03-08 23:53
Pretty sure that's an Enigmatica specific quest setup issue but I'll give it a test just in case. Good to know everything else is working for you now. Feel free to keep using that early build for now while I work on other stuff.

**Comment by Funwayguy** [comment] 2019-03-09 01:54
@Dimentive Tested using the 3.5.153 version of SE installed in Enigmatica 2 Light and the quest appears to have worked just fine for me.

I'm going to close this issue considering the original issue has been solved and this new one appears to be Enigmatica specific.

**Closed as completed by Funwayguy** 2019-03-09 01:54 UTC

**Comment by Dimentive** [comment] 2019-03-09 02:21
I’m playing Enigmatica 2, not the light version. Still, it’s probably the same when it comes to this quest.

I’m at least glad that the original issue was fixed and that almost every quest can be obtained now!
I’ll go ahead and post this new problem with the Barista Trainee quest as an issue on the Enigmatica 2 issue tracker instead.
