### ISSUE TITLE
[Request] R to show recipes

### ISSUE THREAD

**Issue by Thyriel** [Funwayguy/BetterQuesting#243] opened 2017-10-13 11:44 UTC
Would it be possible to add pressing R on items in quests to open the recipe when JEI is installed ?

**Comment by Funwayguy** [comment] 2017-10-29 00:10
This used to be a thing in the 1.7.10 version but I opted not to port it across, partly out of laziness but mostly because I wanted to reduce build dependencies in BQ.

**Comment by soraphis** [comment] 2017-11-21 18:01
duplicate of #221

**Closed as completed** 2019-01-22 03:56 UTC
