### ISSUE TITLE
1.10.2 Cooldown/Repeat Not Working

### ISSUE THREAD

**Issue by Bartz24** [Funwayguy/BetterQuesting#141] opened 2017-01-30 01:10 UTC
![cooldown](https://cloud.githubusercontent.com/assets/18143350/22409888/d96cee20-e65e-11e6-8d6e-8059399fc598.PNG)

The cooldown is negative and the quest cannot be completed again.
Cooldown was set to 480 in the properties.

**Comment by Funwayguy** [comment] 2017-01-30 02:07
If I had to guess I'd say my quest caching system missed updating repeatable tasks. Hopefully can get this fixed by next update

**Comment by Bartz24** [comment] 2017-01-30 23:05
It works now, but the cooldown doesn't start at 8 min, but around 24 sec instead...

Seems to divide by 20

480/20 is 24 sec

**Comment by Funwayguy** [comment] 2017-02-04 09:55
That's not a bug, the cooldown is in game ticks not seconds. 20 ticks = 1 second

**Closed as completed by Funwayguy** 2017-02-04 09:55 UTC

**Comment by Bartz24** [comment] 2017-02-04 12:31
Ok, so it's just a visual bug. repeatTime is set to 600, and it thinks 600 is 10 min.
![2017-02-04_07 30 46](https://cloud.githubusercontent.com/assets/18143350/22618494/c0d0938e-eaab-11e6-975e-6631d8f73456.png)

**Comment by Funwayguy** [comment] 2017-02-05 11:49
(does math in head) yeaaaaa... that's wrong. I should probably fix that next update. Thanks for the heads up
