### ISSUE TITLE
bug panning quests while zoomed

### ISSUE THREAD

**Issue by Spongman** [Funwayguy/BetterQuesting#305] opened 2018-02-21 06:12 UTC
sometimes you can't pan the quest-lines window completely when zoomed in.

in the quest lines view, if you zoom in a bunch (~200%) on a page with a lot of quests on it, you can't pan to the left. eg, this is as far left as i can pan on this page:

![image](https://user-images.githubusercontent.com/1088194/36465674-0ed5992e-168b-11e8-9a46-70fa8ce3e182.png)

**Comment by Funwayguy** [comment] 2018-02-21 06:47
This might actually be caused by the quest line being designed with icons off in negative coordinates. The BQ2 GUI never really supported that but I'm hoping to have it resolved with its replacement screen which is next on my todo list.

**Comment by Spongman** [comment] 2018-02-21 17:34
another issue is that the hit-testing for the quest icons isn't clipped to the quest line window, so those quests that are panned off to the left take precedence over the 'category' menu items.

for example, see the 'Stuff and Things' menu item on the left there, if you click on the right-hand side of that menu button, instead of selecting that category, it actually clicks one of the quests that is panned under the left edge of the quest window.

**Closed as completed** 2019-01-22 03:57 UTC
