### ISSUE TITLE
Crashing when putting an item retrieval

### ISSUE THREAD

**Issue by Firstwarzone** [Funwayguy/BetterQuesting#621] opened 2019-07-12 16:38 UTC
[crash-2019-07-12_12.30.43-client.txt](https://github.com/Funwayguy/BetterQuesting/files/3387267/crash-2019-07-12_12.30.43-client.txt)
whenever I add an item to item retrieval my game crashes

**Comment by Funwayguy** [comment] 2019-07-13 07:10
Seems I may have missed a spot when making the JEI support a soft dependency. The issue is actually located within the Standard Expansion so luckily it doesn't interfere with my current WIP code. I'll have a look at it tomorrow if I get a chance. For now you can just drop JEI in to keep it quiet.

**Comment by Firstwarzone** [comment] 2019-07-13 19:50
thanks

**Comment by VossTheRam** [comment] 2019-07-16 09:21
I am having a similar issue, when I look at the list of items to choose for retrievals or rewards it crashes my client after 2 seconds. I showed my crash report to a friend and apparently it doesn't actually specify why it crashed. I was testing the mod on a single player game, I reloaded and tried again twice and same thing kept happening.
[crash-2019-07-16_03.54.15-client.txt](https://github.com/Funwayguy/BetterQuesting/files/3396306/crash-2019-07-16_03.54.15-client.txt)

**Comment by Funwayguy** [comment] 2019-07-16 13:28
That appears to be a separate issue though the presence of optifine may have something to do with it. I'll have to remember to deofuscate the method calls but as your friend alluded to earlier, it doesn't seem to be pointing anywhere mod related.

**Comment by VossTheRam** [comment] 2019-07-16 17:16
We are currently working on a custom modpack with almost 300 mods, we wanted to add a quest system to help people learn the mods and add an rpg flare, everything is built around optifine so when its removed all the launcher does is crash lol. We decided to go with your mod because 1. It looks amazing and customizable with branching paths and 2. You still work on the mod/older versions (which we find admirable). We will simply be waiting until the issue gets resolved. Thanks for the reply!

**Comment by Funwayguy** [comment] 2019-07-17 02:04
@VossTheRam 
The deobfuscated method calls goes nowhere and the line numbers are off (vanilla files are modified). This doesn't appear to have anything directly to do with BQ besides crashing while its GUI was open. I cannot help you fix it nor do I have any leads on where to even start debugging. Optifine is also not a mod I do support for.

I would also like to state that designing a modpack around the mandatory requirement of Optifine is generally a bad idea. A number of mod devs will not support it and I know for a fact it can break BQ's GUI rendering for some people, particularly versions that require the OpenGL stencil buffer. Sorry but you're on your own for this one.

**Comment by VossTheRam** [comment] 2019-07-17 06:19
Your mod is the only one out of 292 others that did not work with Optifine. It seems very silly to not have any sort of support for optifine when over 90% of all tested mods worked. Thanks for clarifying though, we will be looking elsewhere.

**Comment by Funwayguy** [comment] 2019-07-17 13:09
Simply working and actually supported are two very different things. You're expriencing a crash on a GUI where literally 300 mods worth of items are listed and rendered using a 3rd party pipeline that I have no control over and cannot use in-dev. Not only that but due to the amount of modifications to the vanilla pipeline, the crashlogs are useless. I have no idea what you're expecting me to do here.

**Comment by Funwayguy** [comment] 2019-07-17 13:11
Also, new BQ beta build includes a fix for this thread's original issue so I can close this now.

**Closed as completed** 2019-07-17 13:11 UTC
